# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestwebsite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testDialog(self):
    # Test name: Test Dialog
    # Step # | name | target | value
    # 1 | open | https://qauto2.forstudy.space/ | 
    self.driver.get("https://qauto2.forstudy.space/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.-guest | 
    self.driver.find_element(By.CSS_SELECTOR, ".-guest").click()
    # 4 | click | css=.btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    # 5 | click | id=addCarMileage | 
    self.driver.find_element(By.ID, "addCarMileage").click()
    # 6 | type | id=addCarMileage | 1
    self.driver.find_element(By.ID, "addCarMileage").send_keys("1")
    # 7 | click | css=.modal-footer > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .btn-primary").click()
    # 8 | close | https://qauto2.forstudy.space/ | 
    self.driver.close()
  
  def test_testLogout(self):
    # Test name: Test Logout
    # Step # | name | target | value
    # 1 | open | https://qauto2.forstudy.space/ | 
    self.driver.get("https://qauto2.forstudy.space/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.-guest | 
    self.driver.find_element(By.CSS_SELECTOR, ".-guest").click()
    # 4 | click | id=userNavDropdown | 
    self.driver.find_element(By.ID, "userNavDropdown").click()
    # 5 | click | css=.dropdown-item:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(5)").click()
    # 6 | close | https://qauto2.forstudy.space/ | 
    self.driver.close()
  
  def test_testSignup(self):
    # Test name: Test Signup
    # Step # | name | target | value
    # 1 | open | https://qauto2.forstudy.space/ | 
    self.driver.get("https://qauto2.forstudy.space/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.btn-outline-white | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-white").click()
    # 4 | type | id=signinEmail | liliiabilyk@gmail.com
    self.driver.find_element(By.ID, "signinEmail").send_keys("liliiabilyk@gmail.com")
    # 5 | type | id=signinPassword | Lilypad219
    self.driver.find_element(By.ID, "signinPassword").send_keys("Lilypad219")
    # 6 | click | css=.btn-link:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-link:nth-child(1)").click()
    # 7 | click | id=signupName | 
    self.driver.find_element(By.ID, "signupName").click()
    # 8 | type | id=signupName | Liliia
    self.driver.find_element(By.ID, "signupName").send_keys("Liliia")
    # 9 | click | id=signupLastName | 
    self.driver.find_element(By.ID, "signupLastName").click()
    # 10 | type | id=signupLastName | Bilyk
    self.driver.find_element(By.ID, "signupLastName").send_keys("Bilyk")
    # 11 | click | id=signupEmail | 
    self.driver.find_element(By.ID, "signupEmail").click()
    # 12 | type | id=signupEmail | oshomkovaa93@kitnastar.com
    self.driver.find_element(By.ID, "signupEmail").send_keys("oshomkovaa93@kitnastar.com")
    # 13 | click | id=signupPassword | 
    self.driver.find_element(By.ID, "signupPassword").click()
    # 14 | type | id=signupPassword | Liliia123456
    self.driver.find_element(By.ID, "signupPassword").send_keys("Liliia123456")
    # 15 | click | id=signupRepeatPassword | 
    self.driver.find_element(By.ID, "signupRepeatPassword").click()
    # 16 | type | id=signupRepeatPassword | Liliia123456
    self.driver.find_element(By.ID, "signupRepeatPassword").send_keys("Liliia123456")
    # 17 | click | css=.btn-primary:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()
    # 18 | click | id=userNavDropdown | 
    self.driver.find_element(By.ID, "userNavDropdown").click()
    # 19 | close | https://qauto2.forstudy.space/ | 
    self.driver.close()
  
  def test_testVideoonmainpage(self):
    # Test name: Test Video on main page
    # Step # | name | target | value
    # 1 | open | https://qauto2.forstudy.space/ | 
    self.driver.get("https://qauto2.forstudy.space/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 4 | click | css=.ytp-large-play-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".ytp-large-play-button").click()
    # 5 | click | css=.video-stream | 
    self.driver.find_element(By.CSS_SELECTOR, ".video-stream").click()
    # 6 | close | https://qauto2.forstudy.space/ | 
    self.driver.close()
  
  def test_testAboutWebpage(self):
    # Test name: Test About Webpage
    # Step # | name | target | value
    # 1 | open | https://qauto2.forstudy.space/ | 
    self.driver.get("https://qauto2.forstudy.space/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.header-link:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".header-link:nth-child(2)").click()
    # 4 | close | https://qauto2.forstudy.space/ | 
    self.driver.close()
  
